feat: generate token and create own token
VisualGameData/VIGAD pull request #140
Opened 2023-04-27 14:25 UTC by BeierKevin

# PR description
*Describe your changes in detail here*

Now you can regenerate a cryptographic token or you are able to create your own token by writing in the text field.
Currently, the rules are very simple, they have to be specified by the team in a more consice way. Additionally, I set it up so that the notification system is incorporated in this.

# Definition Of Done (DoD)
*This PR can be squashed / merged if*
- [ ] a developer is assigned
- [ ] the PR is NOT estimated
- [ ] the PR is labeled
- [ ] the PR is NOT assigned to the current sprint
- [ ] a meaningful title has been set according to https://www.conventionalcommits.org/
- [ ] the PR is described in detail
- [ ] the PR links to an issue
- [ ] the PR has been reviewed

*Add additional conditions here if necessary for this PR*

Fix: #118

2023-04-27 14:27 UTC, BeierKevin commented
The current rules for the token are just placeholders because I am unsure what the rules should be therefore we need to decide what is important

2023-04-28 10:11 UTC, Claiyc commented
> The current rules for the token are just placeholders because I am unsure what the rules should be therefore we need to decide what is important
> 
>     1. min characters
> 
>     2. what characters have to be in
> 
>     3. numbers ?
> 
>     4. etc.

see #118 reply

2023-04-28 14:49 UTC, BeierKevin commented
I ran into something very strange but i don't know why

with this updated function so every generated token has all the properties
<img width="659" alt="image" src="https://user-images.githubusercontent.com/70775490/235180054-e91ddba3-44e1-475c-ab43-b11a8d53305d.png">


I reach the maximum call stack size

<img width="400" alt="image" src="https://user-images.githubusercontent.com/70775490/235180142-0ce41e30-ca97-4c4a-bfa4-80c2f5b6ebdd.png">

2023-05-03 10:55 UTC, Claiyc requested changes
session stopped message should not appear when session is not running

2023-05-03 10:59 UTC, Claiyc commented on src/App.vue
> +        if (isSessionActive.value) stopSession();
no. Just no

2023-05-03 11:35 UTC, Claiyc approved these changes
lgtm

2023-05-03 12:42 UTC, merged