Feat/56 configuration for regex inputs
VisualGameData/VIGAD pull request #67
Opened 2022-12-12 14:18 UTC by BeierKevin

# PR description
*Describe your changes in detail here*

The proper connection between backend regex (value|constraint) and the UI has been made. Additionally, in the run view when the start button is pressed a proper output what has been captured is noted down.

# Definition Of Done (DoD)
*This PR can be squashed / merged if*
- [ ] a developer is assigned
- [ ] the PR is NOT estimated
- [ ] the PR is labeled
- [ ] the PR is assigned to the current sprint
- [ ] a meaningful title has been set according to https://www.conventionalcommits.org/
- [ ] the PR is described in detail
- [ ] the PR links to an issue
- [ ] the PR has been reviewed

*Add additional conditions here if necessary for this PR*

fixes: #56

2022-12-12 20:36 UTC, Claiyc requested changes
Timestamp does not work (timestamp for older log entrys gets replaced for every new one that's being added):
![grafik](https://user-images.githubusercontent.com/58397976/207149144-0b6a2510-97d2-4be1-9413-ae676a0ff03a.png)
(notice how the time is always the same)

Also we shouldn't display anything if no value is found (check for rating = -1)

2022-12-12 20:36 UTC, Claiyc commented on src/components/LogOutput.vue
> +            console.log(Math.floor(Date.now() / 1000));
```suggestion
```

2022-12-12 20:36 UTC, Claiyc commented on src/proc/TesseractHandler.ts
> +                        console.log(results);
```suggestion
```

2022-12-12 20:36 UTC, Claiyc commented on src/proc/regex/Regex.ts
> +            result = [];
this is ugly as hell

2022-12-12 20:40 UTC, BeierKevin commented
Why should be display nothing if nothing is matched, via the rating -1 the user knows that something is wrong with the regex

2022-12-12 20:56 UTC, Claiyc requested changes
Timestamp still wrongly updated.

Regex matching does not seem to work as expected. See #66

2022-12-12 20:56 UTC, Claiyc commented on src/components/capture-area/CaptureAreaSearchValue.vue
> +});
```suggestion
```

2022-12-12 20:56 UTC, Claiyc commented on src/proc/regex/Regex.ts
> +        console.log('generated matches for regex: ' + this.id);
```suggestion
```

2022-12-12 20:59 UTC, BeierKevin commented on src/components/capture-area/CaptureAreaSearchValue.vue
> +});
Haven't fixed the timestamps yet

2022-12-13 16:57 UTC, Claiyc approved these changes

2022-12-13 16:57 UTC, merged