feat(tests): setup vitest unit testing framework with sample unit test
VisualGameData/VIGAD pull request #95
Opened 2023-04-14 07:28 UTC by BeierKevin

# PR description
*Describe your changes in detail here*

I have set up the Vitest Unit testing Framework, which will provide Unit Testing capabilities for Vue Components (Component Testing) and Unit Testing for TypeScript Files.

Additionally, I have set up the possibilities that there are multiple scripts to run 

test: runs the test files
test-ui: opens a simple GUI which is hosted via local host to run tests and see where they are failing 
test-coverage: Generates an HTML Website with a detailed explanation about what code has been covered etc. and can be viewed via an HTML file which is generated in the directory test/unit/coverage

# Definition Of Done (DoD)
*This PR can be squashed / merged if*
- [ ] a developer is assigned
- [ ] the PR is NOT estimated
- [ ] the PR is labeled
- [ ] the PR is assigned to the current sprint
- [ ] a meaningful title has been set according to https://www.conventionalcommits.org/
- [ ] the PR is described in detail
- [ ] the PR links to an issue
- [ ] the PR has been reviewed

*Add additional conditions here if necessary for this PR*

2023-04-17 10:00 UTC, Claiyc requested changes
Please document sufficiently, what each of the tests is actually testing. We don't want to have unnecessary tests.

2023-04-17 17:35 UTC, BeierKevin commented
I have removed almost all the commited component unit tests, but I left one in.

2023-04-18 07:12 UTC, Claiyc requested changes
There is a weird margin in the sidebar:
![grafik](https://user-images.githubusercontent.com/58397976/232699678-1eab53a2-3ad3-434b-9bf2-61215eddba96.png)

2023-04-18 07:13 UTC, BeierKevin commented
Hmm, idk I guess I can have a look at it but, currently I don't encounter any bugs in that way.

2023-04-18 07:14 UTC, Claiyc commented on src/components/ViewComponent/ViewComponent.test.ts
individual tests should be well documented, clearly describing intensions, what it's actually testing and expected results

2023-04-18 07:17 UTC, BeierKevin commented on src/components/ViewComponent/ViewComponent.test.ts
Shouldn't the text in the described be sufficient enough because it states what should be displayed

2023-04-18 07:52 UTC, Claiyc commented on src/components/ViewComponent/ViewComponent.test.ts
No, that is not sufficient

2023-04-18 16:16 UTC, BeierKevin commented
@Claiyc so i recloned the repo and tested on my PC aswell on my Laptop and i could reproduce the bug you encountered, could you maybe try it on your pc if you encounter the same bug ?

2023-04-19 18:48 UTC, roman533 commented
<img width="1139" alt="Bildschirmfoto 2023-04-19 um 20 46 44" src="https://user-images.githubusercontent.com/62931919/233171475-402fca6f-fcbd-498f-bbc6-9eeac968f072.png">
Width seems fine on my setup

2023-04-19 19:58 UTC, Claiyc commented
re-cloning seems to solve the issue

2023-04-19 20:06 UTC, Claiyc requested changes
Would stick to the present tense regarding the tests but other than that I'm fine with this

2023-04-19 20:06 UTC, Claiyc commented on src/components/ViewComponent/ViewComponent.test.ts
> +  it('renders the title prop', () => {
```suggestion
  it('Render title prop', () => {
```

2023-04-19 20:06 UTC, Claiyc commented on src/components/ViewComponent/ViewComponent.test.ts
> +  it('renders default slot content', () => {
```suggestion
  it('Render default slot content', () => {
```

2023-04-19 20:06 UTC, Claiyc commented on src/components/ViewComponent/ViewComponent.test.ts
> +  it('renders actions slot content', () => {
```suggestion
  it('Render action slot content', () => {
```

2023-04-19 20:06 UTC, Claiyc commented on src/components/ViewComponent/ViewComponent.test.ts
these tests still seem a bit unnecessary, but I guess we can leave them in for now

2023-04-19 20:13 UTC, Claiyc approved these changes
lgtm

2023-04-19 20:15 UTC, merged